### ISSUE TITLE
Request Code to generate the table of the seen and unseen classes

### ISSUE THREAD

**Issue by LordsMikel** [Snowstormfly/Cross-modal-retrieval-MLAGT#3]
Hi,

I admire your repository and research work; it is fantastic. However, I couldn't find the code to generate the tables of seen and unseen classes to test the model. Could you please provide the code to generate them and test the model? I would greatly appreciate it.

Best wishes,
Mikel

**Comment by Snowstormfly** [comment]
Hi, Mikel

In our experiments, we did not use any code to generate "seen" and "unseen" classes. The division of "seen" and "unseen" classes was done manually based on the classification method in Table 3 of the paper, where we divided the 20 categories of the RSketch_Ext dataset into 4-folds for training and testing to evaluate the performance of our model. Therefore, if you want to test the model's effectiveness, you should also manually modify the categories of the training and testing sets to meet the corresponding requirements before testing.

Best wishes,

Bo Yang
